---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

data("nyc_airbnb")

df_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location/2) |> 
  select(
    borough = neighbourhood_group, neighbourhood,
    stars, price, room_type, lat, long
  )
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_vec = df_airbnb |> pull(borough) |> unique()

selectInput(
  inputId = "borough_choice",
  label = h3("Select Borough"),
  choices = borough_vec,
  selected = "Manhattan"
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderText({
  input[["borough_choice"]]
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```